### ISSUE TITLE
Need BLUETOOTH PRIVILEGED permission

### ISSUE THREAD

**Issue by fbiego** [kshoji/BLE-HID-Peripheral-for-Android#14]
```
D/HidPeripheral: Need BLUETOOTH PRIVILEGED permission: Neither user 10152 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
    java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10152 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
        at android.os.Parcel.readException(Parcel.java:1683)
        at android.os.Parcel.readException(Parcel.java:1636)
        at android.bluetooth.IBluetooth$Stub$Proxy.setPairingConfirmation(IBluetooth.java:1616)
        at android.bluetooth.BluetoothDevice.setPairingConfirmation(BluetoothDevice.java:1273)
        at jp.kshoji.blehid.HidPeripheral$5.onConnectionStateChange(HidPeripheral.java:609)
        at android.bluetooth.BluetoothGattServer$1.onServerConnectionState(BluetoothGattServer.java:105)
        at android.bluetooth.IBluetoothGattServerCallback$Stub.onTransact(IBluetoothGattServerCallback.java:82)
        at android.os.Binder.execTransact(Binder.java:570)
```

Android docs says 'Not for use by third-party applications.' 
[`BLUETOOTH PRIVILEGED`](https://developer.android.com/reference/android/Manifest.permission.html#BLUETOOTH_PRIVILEGED)

How do I make it work?

**Comment by tobiasBora** [comment]
Not sure, but this suggest that it's possible to add it via adb https://github.com/kshoji/BLE-HID-Peripheral-for-Android/issues/8

**Comment by iroidzeel** [comment]
Im trying to use this app but nothing happens no crash logs and nothing how did you get this BLUETOOTH PRIVILEGED issue?

it is working now for you?

**Comment by fbiego** [comment]
happens during pairing because `setPairingConfirmation(true)` requires BLUETOOTH PRIVILEGED.
Even after granting the permission by installing as a system app, pairing fails #1
